# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["lib/*"]
default-members = ["lib/asimov-sdk"]
resolver = "2"

[workspace.package]
version = "24.0.0-dev.17"
authors = ["ASIMOV by Haltia.AI <support@asimov.so>"]
edition = "2021"
rust-version = "1.70"
description = "ASIMOV Software Development Kit (SDK) for Rust"
#documentation = "https://docs.rs/asimov-sdk/"
readme = true
homepage = "https://sdk.asimov.so"
repository = "https://github.com/AsimovPlatform/asimov.rs"
license = "Unlicense"
keywords = []
categories = []
publish = true

[workspace.dependencies]
asimov-core = { path = "lib/asimov-core" }
asimov-sdk = { path = "lib/asimov-sdk" }
asimov-sys = { path = "lib/asimov-sys" }
cfg_aliases = "0.2"
dogma = { version = "0.1", default-features = false }
know = { version = "0", default-features = true }
stability = "0.2"

[patch.crates-io]
asimov-core = { path = "lib/asimov-core" }
asimov-sdk = { path = "lib/asimov-sdk" }
asimov-sys = { path = "lib/asimov-sys" }
